name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vpn-snmp-monitoring:latest

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY $USERNAME@$HOST << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/vpn-snmp-monitoring:latest
          docker-compose down
          docker-compose up -d
        EOF
